kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: v1.21-mgmt
nodes:
- role: control-plane
  image: kindest/node:v1.21.2
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  extraPortMappings:
  - containerPort: 80
    hostPort: 8080
    protocol: TCP
  - containerPort: 443
    hostPort: 8443
    protocol: TCP
