---
apiVersion: mydev.org/v1alpha1
kind: ClusterClaim
metadata:
  name: kzap-eks-medium
  namespace: eks-cluster
  labels:
    cluster-owner: kzap
spec:
  id: kzap-eks-medium
  compositionSelector:
    matchLabels:
      provider: aws
      cluster: eks
  parameters:
    nodeSize: medium
    minNodeCount: 3